import { existsSync } from 'node:fs'
import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { join } from 'node:path'
import type { ChapterSummary, SceneSummary } from '@shared/schema/retrieval'
import { projectPaths } from './paths'

// Rolling scene/chapter summaries generated by a deterministic extractive
// heuristic (first sentences of the source text) — a placeholder for a real
// summarization model, in the same "clearly labeled simulation" style as
// main/retrieval/vectorize.ts and main/agent/simulator.ts.
//
// getOrGenerateSceneSummary()'s signature only takes the scene's prose text,
// not its SceneMeta.updatedAt (sceneStore.ts, which owns SceneMeta, is out
// of scope to edit here), so "rolling" is implemented via a content
// fingerprint of the prose itself rather than the scene's real updatedAt
// timestamp: sourceUpdatedAt stores a hash of the prose, and the summary is
// only regenerated when that hash no longer matches what's on disk. This
// still satisfies "not permanently stale, without recomputing on every
// read" — it just keys off content instead of a metadata timestamp.

function hashContent(text: string): string {
  let hash = 5381
  for (let i = 0; i < text.length; i++) {
    hash = (hash * 33) ^ text.charCodeAt(i)
  }
  return (hash >>> 0).toString(16)
}

function extractSummary(text: string, maxSentences: number, maxLen: number): string {
  const trimmed = text.trim()
  if (!trimmed) return ''
  const sentences = trimmed.match(/[^.!?]+[.!?]*/g) ?? [trimmed]
  const excerpt = sentences.slice(0, maxSentences).join(' ').trim()
  return excerpt.length > maxLen ? `${excerpt.slice(0, maxLen).trim()}…` : excerpt
}

async function readJsonSafe<T>(path: string): Promise<T | null> {
  const raw = await readFile(path, 'utf-8').catch(() => null)
  return raw ? (JSON.parse(raw) as T) : null
}

function sceneSummaryPath(projectRoot: string, sceneId: string): string {
  return join(projectPaths(projectRoot).summariesDir, 'scenes', `${sceneId}.json`)
}

function chapterSummaryPath(projectRoot: string, chapterId: string): string {
  return join(projectPaths(projectRoot).summariesDir, 'chapters', `${chapterId}.json`)
}

export function chapterSummaryExists(projectRoot: string, chapterId: string): boolean {
  return existsSync(chapterSummaryPath(projectRoot, chapterId))
}

export async function getOrGenerateSceneSummary(
  projectRoot: string,
  sceneId: string,
  proseText: string
): Promise<SceneSummary> {
  const filePath = sceneSummaryPath(projectRoot, sceneId)
  const sourceUpdatedAt = hashContent(proseText)

  const existing = await readJsonSafe<SceneSummary>(filePath)
  if (existing && existing.sourceUpdatedAt === sourceUpdatedAt) return existing

  const summary: SceneSummary = {
    sceneId,
    summary: extractSummary(proseText, 2, 280),
    sourceUpdatedAt,
    updatedAt: new Date().toISOString()
  }
  await mkdir(join(projectPaths(projectRoot).summariesDir, 'scenes'), { recursive: true })
  await writeFile(filePath, JSON.stringify(summary, null, 2), 'utf-8')
  return summary
}

export async function getOrGenerateChapterSummary(
  projectRoot: string,
  chapterId: string,
  sceneSummaries: SceneSummary[]
): Promise<ChapterSummary> {
  const filePath = chapterSummaryPath(projectRoot, chapterId)
  const sourceUpdatedAt = [...sceneSummaries]
    .sort((a, b) => a.sceneId.localeCompare(b.sceneId))
    .map((s) => `${s.sceneId}:${s.sourceUpdatedAt}`)
    .join('|')

  const existing = await readJsonSafe<ChapterSummary>(filePath)
  if (existing && existing.sourceUpdatedAt === sourceUpdatedAt) return existing

  const summary: ChapterSummary = {
    chapterId,
    summary: extractSummary(sceneSummaries.map((s) => s.summary).join(' '), 4, 400),
    sourceUpdatedAt,
    updatedAt: new Date().toISOString()
  }
  await mkdir(join(projectPaths(projectRoot).summariesDir, 'chapters'), { recursive: true })
  await writeFile(filePath, JSON.stringify(summary, null, 2), 'utf-8')
  return summary
}
